In [0]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

In [0]:
DATADIR = '/content/drive/My Drive/UCmerced/UCMerced_LandUse/Images/'

CATEGORIES = [ 'agricultural',  'airplane',    'baseballdiamond', 'beach',   'buildings',          'chaparral',         'denseresidential',
                'forest',        'freeway',     'golfcourse',      'harbor',  'intersection',       'mediumresidential', 'mobilehomepark',
                'overpass',      'parkinglot',  'river',           'runway',  'sparseresidential',  'storagetanks',      'tenniscourt' ]


In [0]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

Using TensorFlow backend.


In [0]:
path = os.path.abspath('.cnn.py')

In [0]:
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file

In [0]:
img_rows = 256
img_cols = 256
num_class = 21
path = os.path.abspath('.cnn.py') #absolute path of program
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file
x_train = []
y_train = []
x_test = []
y_test = []
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')
dirs=dirs[:-1]
print(len(dirs))
'''

'''

21


'\n\n'

In [0]:
label = 0
for i in dirs:
	n = 0
	count = 0
	for pic in glob.glob(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'+i+'/*.tif'):
		im = Image.open(pic)
		im = np.array(im)
		if((im.shape[0]==256) and (im.shape[1] ==256) and count <90): #get only 90 data
			r = im[:,:,0]
			g = im[:,:,1]
			b = im[:,:,2]
			#if(n<5): # 5 data in beginning set as test data
			#	x_test.append([r,g,b])
			#	y_test.append([label])
			#else: #remaining data set as training data
			x_train.append([r,g,b])
			y_train.append([label])
			n = n + 1
			count = count + 1
		#print(count)
	label = label + 1

In [0]:
xtrainlist=x_train
y_trainlsit=y_train

In [0]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [0]:
x_train.shape
y_train.shape

(1890, 1)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2, random_state = 142)

In [0]:
y_train[0:10]

array([[17],
       [20],
       [18],
       [16],
       [ 8],
       [ 4],
       [ 5],
       [10],
       [16],
       [16]])

In [0]:
x_trainbck=X_train
x_testbck=X_test


In [0]:
x_train=np.array(X_train)
x_test=np.array(X_test)

In [0]:
x_train.shape

(1512, 3, 256, 256)

In [0]:
x_train_temp=x_train

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)

input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)

In [0]:
from skimage import feature
import numpy as np
 
class LocalBinaryPatterns:
  def __init__(self, numPoints, radius):
# store the number of points and radius
    self.numPoints = numPoints
    self.radius = radius
  def describe(self, image, eps=1e-7):
		# compute the Local Binary Pattern representation
		# of the image, and then use the LBP representation
		# to build the histogram of patterns
    lbp = feature.local_binary_pattern(image, self.numPoints,
    self.radius, method="uniform")
    return lbp 

In [0]:
desc = LocalBinaryPatterns(24, 8)

In [0]:
x_train_lbp=[]


In [0]:
for i in x_train:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_train_lbp.append(hist)

In [0]:
x_train_lbp=np.array(x_train_lbp)

In [0]:
x_train_lbp.shape

(1512, 256, 256)

In [0]:
x_test_lbp=[]


In [0]:
for i in x_test:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_test_lbp.append(hist)

In [0]:
x_test_lbp=np.array(x_test_lbp)

In [0]:
x_test_lbp.shape

(378, 256, 256)

In [0]:
x_train_lbp.shape

(1512, 256, 256)

In [0]:
x_train_lbp = x_train_lbp.reshape(x_train_lbp.shape[0], img_rows, img_cols, 1)
x_test_lbp = x_test_lbp.reshape(x_test_lbp.shape[0], img_rows, img_cols, 1)

input_shape2 = (img_rows, img_cols, 1)

In [0]:
import time 
import cv2 
from scipy.fftpack import dct 
import numpy as np
#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a = np.zeros((len(x_train_lbp), 256, 256, 1))
for i in range(len(x_train_lbp)):
    for j in range(1):
        a[i, :, :, j] = cv2.dct(x_train_lbp[i, :, :, j])

In [0]:
x_dct=a

In [0]:
x_dct.shape

(1512, 256, 256, 1)

In [0]:
x_dct_final = np.random.random((len(x_dct), 32, 32, 1))

In [0]:
for i in range(1512):
  for j in range(32):
    for k in range(32):
      for l in range(1):
        x_dct_final[i,j,k,l]=x_dct[i,j,k,l]

In [0]:
x_dct_final.shape

(1512, 32, 32, 1)

In [0]:
input_shape1 = (img_rows, img_cols, 3)
input_shape2 = (32, 32, 1)
input_shape3 = (img_rows, img_cols, 3)

In [0]:

#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a1 = np.zeros((len(x_test_lbp), 256, 256, 1))
for i in range(len(x_test_lbp)):
    for j in range(1):
        a1[i, :, :, j] = cv2.dct(x_test_lbp[i, :, :, j])

In [0]:
x_dct_t=a1

In [0]:
x_dct_t.shape

(378, 256, 256, 1)

In [0]:
x_dct_test = np.random.random((len(x_dct_t), 32, 32, 1))

In [0]:
for i in range(378):
  for j in range(32):
    for k in range(32):
      for l in range(1):
        x_dct_test[i,j,k,l]=x_dct_t[i,j,k,l]

In [0]:
x_dct_test.shape

(378, 32, 32, 1)

In [0]:
import time 
import cv2 
from scipy.fftpack import dct 
import numpy as np
#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a11 = np.zeros((len(x_train), 256, 256, 3))
for i in range(len(x_train)):
    for j in range(3):
        a11[i, :, :, j] = cv2.dct(x_train[i, :, :, j])

In [0]:
x_dct11=a11

In [0]:
x_dct11.shape

(1512, 256, 256, 3)

In [0]:
input_shape = (img_rows, img_cols, 3)

In [0]:
x_dct_final_train = np.random.random((len(x_dct11), 32, 32, 3))

In [0]:
for i in range(1512):
  for j in range(32):
    for k in range(32):
      for l in range(3):
        x_dct_final_train[i,j,k,l]=x_dct11[i,j,k,l]

In [0]:
x_dct_final_train.shape

(1512, 32, 32, 3)

In [0]:
input_shape1 = (img_rows, img_cols, 3)
input_shape2 = (32, 32, 3)

In [0]:

#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a1111 = np.zeros((len(x_test), 256, 256, 3))
for i in range(len(x_test)):
    for j in range(3):
        a1111[i, :, :, j] = cv2.dct(x_test[i, :, :, j])

In [0]:
x_dct_t111=a1111

In [0]:
x_dct_t111.shape

(378, 256, 256, 3)

In [0]:
x_dct_test_final = np.random.random((len(x_dct_t111), 32, 32, 3))

In [0]:
for i in range(378):
  for j in range(32):
    for k in range(32):
      for l in range(3):
        x_dct_test_final[i,j,k,l]=x_dct_t111[i,j,k,l]

In [0]:
x_dct_test_final.shape

(378, 32, 32, 3)

In [0]:
ashape=np.array([x_dct_test_final.shape, x_dct_final_train.shape, x_dct_final.shape, x_dct_test.shape, x_train.shape, x_test.shape])


In [0]:
for i in ashape:
  print(i)

[378  32  32   3]
[1512   32   32    3]
[1512   32   32    1]
[378  32  32   1]
[1512  256  256    3]
[378 256 256   3]


In [0]:
inputshape1=(256,256,3)
inputshape2=(32,32,3)
inputshape3=(32,32,1)

In [0]:
from keras.layers import Input, Conv2D, Dense, concatenate
from keras.models import Model

In [0]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,LeakyReLU
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

In [0]:
from keras.layers import *
inputTensor1 = Input(input_shape1)
#inputTensor2 = Input(input_shape2)
#nputTensor3 = Input(input_shape)


In [0]:
inputTensor2 = Input((32,32,3))

In [0]:
inputTensor3 = Input((32,32,1))
print(inputTensor3)

Tensor("input_14:0", shape=(?, 32, 32, 1), dtype=float32)


In [0]:
print(inputTensor1)
print(inputTensor2)
print(inputTensor3)


Tensor("input_10:0", shape=(?, 256, 256, 3), dtype=float32)
Tensor("input_15:0", shape=(?, 32, 32, 3), dtype=float32)
Tensor("input_14:0", shape=(?, 32, 32, 1), dtype=float32)


In [0]:
model1=(Conv2D(32, kernel_size=(3, 3),activation='relu'))(inputTensor1)
model1=(MaxPooling2D(pool_size=(2,2)))(model1)
model1=(Conv2D(32, (3, 3), activation='relu'))(model1)
model1=(MaxPooling2D(pool_size=(2,2)))(model1)
model1=(Dropout(0.25))(model1)
model1=(Flatten())(model1)
model1=(Dense(128, activation='relu'))(model1)
model1=(Dropout(0.5))(model1)
model1 = Model(inputs=inputTensor1, outputs=model1)


In [0]:
model2=(Conv2D(32, kernel_size=(3, 3),activation='relu'))(inputTensor2)
model2=(MaxPooling2D(pool_size=(2,2)))(model2)
model2=(Conv2D(32, (3, 3), activation='relu'))(model2)
model2=(MaxPooling2D(pool_size=(2,2)))(model2)
model2=(Dropout(0.25))(model2)
model2=(Flatten())(model2)
model2=(Dense(128, activation='relu'))(model2)
model2=(Dropout(0.5))(model2)
model2 = Model(inputs=inputTensor2, outputs=model2)


In [0]:
model3=(Conv2D(32, kernel_size=(3, 3),activation='relu'))(inputTensor3)
model3=(MaxPooling2D(pool_size=(2,2)))(model3)
model3=(Conv2D(32, (3, 3), activation='relu'))(model3)
model3=(MaxPooling2D(pool_size=(2,2)))(model3)
model3=(Dropout(0.25))(model3)
model3=(Flatten())(model3)
model3=(Dense(128, activation='relu'))(model3)
model3=(Dropout(0.5))(model3)
model3 = Model(inputs=inputTensor3, outputs=model3)


In [0]:
#from keras.layers import Activation, Dense, Dropout, Flatten, Input, Merge
x = concatenate([model1.output, model2.output,model3.output])  # merge the outputs of the two models
out = Dense(21,activation='softmax')(x) 

In [0]:
model = Model(inputs=[inputTensor1, inputTensor2,inputTensor3], outputs=[out])

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [0]:
model.fit([x_train,x_dct_final_train,x_dct_final], y_train, epochs=10, batch_size=32,validation_data=([x_test,x_dct_test_final,x_dct_test],y_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 1512 samples, validate on 378 samples
Epoch 1/10





1512/1512 [==============================] - 16s 10ms/step - loss: 14.6202 - acc: 0.0430 - val_loss: 10.0065 - val_acc: 0.0397
Epoch 2/10
1512/1512 [==============================] - 6s 4ms/step - loss: 4.7283 - acc: 0.0847 - val_loss: 2.7607 - val_acc: 0.1878
Epoch 3/10
1512/1512 [==============================] - 6s 4ms/step - loss: 2.5841 - acc: 0.2328 - val_loss: 2.2982 - val_acc: 0.3201
Epoch 4/10
1512/1512 [==============================] - 6s 4ms/step - loss: 1.9515 - acc: 0.4200 - val_loss: 2.0283 - val_acc: 0.3862
Epoch 5/10
1512/1512 [==============================] - 6s 4ms/step - loss: 1.3901 - acc: 0.5860 - val_loss: 1.7488 - val_acc: 0.4762
Epoch 6/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.9271 - acc: 0.7136 - val_loss: 1.5171 - val_acc: 0.5529
Epoch 7/10
1512/1512 [=====================

In [0]:
model.fit([x_train,x_dct_final_train,x_dct_final], y_train, epochs=10, batch_size=32,validation_data=([x_test,x_dct_test_final,x_dct_test],y_test))

Train on 1512 samples, validate on 378 samples
Epoch 1/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.2026 - acc: 0.9398 - val_loss: 1.8825 - val_acc: 0.5794
Epoch 2/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.2348 - acc: 0.9352 - val_loss: 1.9204 - val_acc: 0.5556
Epoch 3/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.1586 - acc: 0.9577 - val_loss: 1.7276 - val_acc: 0.5714
Epoch 4/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.1238 - acc: 0.9597 - val_loss: 1.8630 - val_acc: 0.5794
Epoch 5/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.1296 - acc: 0.9669 - val_loss: 1.9044 - val_acc: 0.5582
Epoch 6/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.1399 - acc: 0.9597 - val_loss: 1.9016 - val_acc: 0.5794
Epoch 7/10
1512/1512 [==============================] - 6s 4ms/step - loss: 0.1107 - acc: 0.9643 - val_loss: 2.0190 - val_acc: 0.5741
Epoch 8/10
1512