In [0]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

In [0]:
DATADIR = '/content/drive/My Drive/UCmerced/UCMerced_LandUse/Images/'

CATEGORIES = [ 'agricultural',  'airplane',    'baseballdiamond', 'beach',   'buildings',          'chaparral',         'denseresidential',
                'forest',        'freeway',     'golfcourse',      'harbor',  'intersection',       'mediumresidential', 'mobilehomepark',
                'overpass',      'parkinglot',  'river',           'runway',  'sparseresidential',  'storagetanks',      'tenniscourt' ]


In [0]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

Using TensorFlow backend.


In [0]:
path = os.path.abspath('.cnn.py')

In [0]:
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file

In [0]:
img_rows = 256
img_cols = 256
num_class = 21
path = os.path.abspath('.cnn.py') #absolute path of program
path = re.sub('[a-zA-Z\s._]+$', '', path) #remove unintended file
x_train = []
y_train = []
x_test = []
y_test = []
dirs = os.listdir(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/')
dirs=dirs[:-1]
print(len(dirs))
'''

'''

21


'\n\n'

In [0]:
label = 0
for i in dirs:
	n = 0
	count = 0
	for pic in glob.glob(path+'/drive/My Drive/ucmerced/UCMerced_LandUse/Images/'+i+'/*.tif'):
		im = Image.open(pic)
		im = np.array(im)
		if((im.shape[0]==256) and (im.shape[1] ==256) and count <90): #get only 90 data
			r = im[:,:,0]
			g = im[:,:,1]
			b = im[:,:,2]
			#if(n<5): # 5 data in beginning set as test data
			#	x_test.append([r,g,b])
			#	y_test.append([label])
			#else: #remaining data set as training data
			x_train.append([r,g,b])
			y_train.append([label])
			n = n + 1
			count = count + 1
		#print(count)
	label = label + 1

In [0]:
xtrainlist=x_train
y_trainlsit=y_train

In [0]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [0]:
x_train.shape
y_train.shape

(1890, 1)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2, random_state = 142)

In [0]:
y_train[0:10]

array([[17],
       [20],
       [18],
       [16],
       [ 8],
       [ 4],
       [ 5],
       [10],
       [16],
       [16]])

In [0]:
x_trainbck=X_train
x_testbck=X_test


In [0]:
x_train=np.array(X_train)
x_test=np.array(X_test)

In [0]:
x_train.shape

(1512, 3, 256, 256)

In [0]:
x_train_temp=x_train

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)

input_shape = (img_rows, img_cols, 3)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, 21)
y_test = keras.utils.to_categorical(y_test, 21)

In [0]:
from skimage import feature
import numpy as np
 
class LocalBinaryPatterns:
  def __init__(self, numPoints, radius):
# store the number of points and radius
    self.numPoints = numPoints
    self.radius = radius
  def describe(self, image, eps=1e-7):
		# compute the Local Binary Pattern representation
		# of the image, and then use the LBP representation
		# to build the histogram of patterns
    lbp = feature.local_binary_pattern(image, self.numPoints,
    self.radius, method="uniform")
    return lbp 

In [0]:
desc = LocalBinaryPatterns(24, 8)

In [0]:
x_train_lbp=[]


In [0]:
for i in x_train:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_train_lbp.append(hist)

In [0]:
x_train_lbp=np.array(x_train_lbp)

In [0]:
x_train_lbp.shape

(1512, 256, 256)

In [0]:
x_test_lbp=[]


In [0]:
for i in x_test:
  gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
  hist = desc.describe(gray)
  x_test_lbp.append(hist)

In [0]:
x_test_lbp=np.array(x_test_lbp)

In [0]:
x_test_lbp.shape

(378, 256, 256)

In [0]:
x_train_lbp.shape

(1512, 256, 256)

In [0]:
x_train_lbp = x_train_lbp.reshape(x_train_lbp.shape[0], img_rows, img_cols, 1)
x_test_lbp = x_test_lbp.reshape(x_test_lbp.shape[0], img_rows, img_cols, 1)

input_shape2 = (img_rows, img_cols, 1)

In [0]:
import time 
import cv2 
from scipy.fftpack import dct 
import numpy as np
#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a = np.zeros((len(x_train_lbp), 256, 256, 1))
for i in range(len(x_train_lbp)):
    for j in range(1):
        a[i, :, :, j] = cv2.dct(x_train_lbp[i, :, :, j])

In [0]:
x_dct=a

In [0]:
x_dct.shape

(1512, 256, 256, 1)

In [0]:
x_dct_final = np.random.random((len(x_dct), 32, 32, 1))

In [0]:
for i in range(1512):
  for j in range(32):
    for k in range(32):
      for l in range(1):
        x_dct_final[i,j,k,l]=x_dct[i,j,k,l]

In [0]:
x_dct_final.shape

(1512, 32, 32, 1)

In [0]:
input_shape1 = (img_rows, img_cols, 3)
input_shape2 = (32, 32, 1)
input_shape3 = (img_rows, img_cols, 3)

In [0]:

#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a1 = np.zeros((len(x_test_lbp), 256, 256, 1))
for i in range(len(x_test_lbp)):
    for j in range(1):
        a1[i, :, :, j] = cv2.dct(x_test_lbp[i, :, :, j])

In [0]:
x_dct_t=a1

In [0]:
x_dct_t.shape

(378, 256, 256, 1)

In [0]:
x_dct_test = np.random.random((len(x_dct_t), 32, 32, 1))

In [0]:
for i in range(378):
  for j in range(32):
    for k in range(32):
      for l in range(1):
        x_dct_test[i,j,k,l]=x_dct_t[i,j,k,l]

In [0]:
x_dct_test.shape

(378, 32, 32, 1)

In [0]:
import time 
import cv2 
from scipy.fftpack import dct 
import numpy as np
#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a11 = np.zeros((len(x_train), 256, 256, 3))
for i in range(len(x_train)):
    for j in range(3):
        a11[i, :, :, j] = cv2.dct(x_train[i, :, :, j])

In [0]:
x_dct11=a11

In [0]:
x_dct11.shape

(1512, 256, 256, 3)

In [0]:
input_shape = (img_rows, img_cols, 3)

In [0]:
x_dct_final_train = np.random.random((len(x_dct11), 32, 32, 3))

In [0]:
for i in range(1512):
  for j in range(32):
    for k in range(32):
      for l in range(3):
        x_dct_final_train[i,j,k,l]=x_dct11[i,j,k,l]

In [0]:
x_dct_final_train.shape

(1512, 32, 32, 3)

In [0]:
input_shape1 = (img_rows, img_cols, 3)
input_shape2 = (32, 32, 3)

In [0]:

#y = np.random.random((5000, 6, 6, 3))
t1 = time.time()
a1111 = np.zeros((len(x_test), 256, 256, 3))
for i in range(len(x_test)):
    for j in range(3):
        a1111[i, :, :, j] = cv2.dct(x_test[i, :, :, j])

In [0]:
x_dct_t111=a1111

In [0]:
x_dct_t111.shape

(378, 256, 256, 3)

In [0]:
x_dct_test_final = np.random.random((len(x_dct_t111), 32, 32, 3))

In [0]:
for i in range(378):
  for j in range(32):
    for k in range(32):
      for l in range(3):
        x_dct_test_final[i,j,k,l]=x_dct_t111[i,j,k,l]

In [0]:
x_dct_test_final.shape

(378, 32, 32, 3)

In [0]:
ashape=np.array([x_dct_test_final.shape, x_dct_final_train.shape, x_dct_final.shape, x_dct_test.shape, x_train.shape, x_test.shape])


In [0]:
for i in ashape:
  print(i)

[378  32  32   3]
[1512   32   32    3]
[1512   32   32    1]
[378  32  32   1]
[1512  256  256    3]
[378 256 256   3]


In [0]:
inputshape1=(256,256,3)
inputshape2=(32,32,3)
inputshape3=(32,32,1)

In [0]:
x_final_train=[]

In [0]:
xt1=[]
xt2=[]

In [0]:
xt1=x_dct_final_train

In [0]:
xt1.shape

(1512, 32, 32, 3)

In [0]:
for i in range(1512):
  x_final.append()

In [0]:
for i in range(1512):
  x_final_train.append(np.dstack((x_dct_final_train[i],x_dct_final[i])))

In [0]:
x_final_train_np=np.array(x_final_train)

In [0]:
x_final_train_np.shape

(1512, 32, 32, 4)

In [0]:
x_final_test=[]

In [0]:
for i in range(378):
  x_final_test.append(np.dstack((x_dct_test_final[i],x_dct_test[i])))

In [0]:
x_final_test_np=np.array(x_final_test)

In [0]:
x_final_test_np.shape

(378, 32, 32, 4)

In [0]:
from keras.layers import Input, Conv2D, Dense, concatenate
from keras.models import Model

In [0]:
from PIL import Image #import Python Image Library
import numpy as np
import os
import glob
import re
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,LeakyReLU
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import backend as K

In [0]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=x_final_train_np.shape[1:]))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(21, activation='softmax'))
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




In [0]:
model.fit(x_final_train_np, y_train, batch_size=50, nb_epoch=100, verbose=1, validation_data=(x_final_test_np, y_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.





Train on 1512 samples, validate on 378 samples
Epoch 1/100





1512/1512 [==============================] - 8s 5ms/step - loss: 14.7661 - acc: 0.0496 - val_loss: 15.4305 - val_acc: 0.0423
Epoch 2/100
1512/1512 [==============================] - 0s 203us/step - loss: 14.5371 - acc: 0.0522 - val_loss: 10.2256 - val_acc: 0.0608
Epoch 3/100
1512/1512 [==============================] - 0s 200us/step - loss: 5.8997 - acc: 0.0470 - val_loss: 3.0435 - val_acc: 0.0397
Epoch 4/100
1512/1512 [==============================] - 0s 205us/step - loss: 3.0429 - acc: 0.0549 - val_loss: 3.0434 - val_acc: 0.0450
Epoch 5/100
1512/1512 [==============================] - 0s 214us/step - loss: 3.0380 - acc: 0.0575 - val_loss: 3.0473 - val_acc: 0.0714
Epoch 6/100
1512/1512 [==============================] - 0s 203us/step - loss: 3.0342 - acc: 0.0569 - val_loss: 3.0447 - val_acc: 0.0397
Epoch 7/100
1512/1512 [==============================] - 0s 214us/step - loss: 3.0272 - acc: 0.0595 - val_loss: 3.0444 - 